### PR TITLE
Move window to center, edge etc.

### PR DESCRIPTION
**Pull request by TaylanTatli**
Added: Move window to top left, bottom left, top right, bottom right, center, top center, bottom center, left center, right center of screen.

### CODE REVIEW

**Comment by TaylanTatli** [comment]
Sorry. Opened by mistake.

**Comment by vando** [comment]
Could you please update "cwm.1" file with the new features?

**Comment by TaylanTatli** [comment]
@vando I will.

**Comment by TaylanTatli** [comment]
@vando Done.

**Comment by Carpetsmoker** [comment]
Any reason in particular this isn't merged @TaylanTatli @vando? I wanted to create exactly the same functionality :-)

**Comment by chneukirchen** [comment]
This repo only tracks OpenBSD, please submit patches there.

**Comment by TaylanTatli** [comment]
@Carpetsmoker You can find the patch here. https://gist.github.com/TaylanTatli/30e24ecac20f9ebb0ee146801750ff84

Now I'm trying to remove border when there is only one client in group but I don't know how to find number of clients in group. I don't have any programming skills. :( Any idea?

**Pull request closed without merging**
